Event_planning/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Event_planning.Data;
using Microsoft.EntityFrameworkCore;

using Event_planning.Models;

namespace Event_planning.Controllers
{
    [Authorize(Roles = "sysadmin")]
    public class AdminController : Controller
    {
        private ApplicationDbContext appDbContext;

        public AdminController(ApplicationDbContext _context)
        {
            appDbContext = _context;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            Console.Beep();
            ApplicationUser user = appDbContext.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            ViewBag.email = user.Email;
            ViewBag.name = user.Name;
            ViewBag.age = user.Age;
            return View();
        }

        [HttpGet]
        public IActionResult EventsManagment()
        {
            try
            {
                IEnumerable<Event> events = appDbContext.Events;
                return View(events);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public IActionResult UsersManagment()
        {
            try
            {
                IEnumerable<ApplicationUser> users = appDbContext.Users.Where(u => u.UserName != User.Identity.Name);
                return View(users);
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }            
        }

        [HttpPost]
        public async Task<IActionResult> UsersManagment(IEnumerable<string> users_id)
        {
            try
            {
                foreach (var id in users_id)
                {
                    ApplicationUser user = await appDbContext.Users.FirstOrDefaultAsync(u => u.Id == id);
                    if (user != null)
                    {
                        appDbContext.Users.Remove(user);
                    }
                }
                await appDbContext.SaveChangesAsync();
                return RedirectToAction("UsersManagment");
            }
            catch (Exception)
            {
                Console.Beep(400, 40);
                return RedirectToAction("UsersManagment");
            }
        }

        [HttpGet]
        public IActionResult EventCreate()
        {
            return RedirectToAction(actionName: "EventCreate", controllerName: "Events");
        }

        [HttpGet]
        public IActionResult EventsList()
        {
            return RedirectToAction(actionName: "EventsList", controllerName: "Events");
        }

        [HttpGet]
        public IActionResult UsersList()
        {
            return RedirectToAction(actionName: "UsersList", controllerName: "Users");
        }
    }
}

Event_planning/Views/Admin/EventsManagment.cshtml
@model IEnumerable<Event_planning.Models.Event>

@{
    ViewData["Title"] = "Events managment";
}

<h2>Events managment</h2>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateTime)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ev in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => ev.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => ev.DateTime)
                </td>
                <td>
                    <a asp-controller="Events" asp-action="EventEdit" asp-route-id="@ev.Id">Edit</a> |
                    <a asp-controller="Events" asp-action="EventDetails" asp-route-id="@ev.Id">Details</a> |               
                    <a asp-controller="Events" asp-action="EventDelete" asp-route-id="@ev.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<p>
    <a asp-controller="Admin" asp-action="Index">start page</a>
</p>

Event_planning/Views/Admin/Index.cshtml
@model IEnumerable<Event_planning.Models.ApplicationUser>

@{
    ViewData["Title"] = "Admin";
}

<h2>Admin</h2>
<h3>@ViewBag.name  @ViewBag.Age</h3>
<h3>@ViewBag.email</h3>

<div class="row">
    <div class="validation" asp-validation-summary="All"></div>
    <div class="col-md-3">
        <form asp-controller="Admin" asp-action="EventCreate" method="get">
            <div class="form-group">
                <label class="control-label">Add new event</label>
                <input type="submit" name="add_event" value="add event" class="form-control btn-info" />
            </div>
        </form>
    </div>
    <div class="col-md-3">
        <form asp-controller="Admin" asp-action="EventsManagment" method="get">
            <div class="form-group">
                <label class="control-label">View all events</label>
                <input type="submit" name="view_events" value="view events" class="form-control btn-info" />
            </div>
        </form>
    </div>
    <div class="col-md-3">
        <form asp-controller="Admin" asp-action="UsersManagment" method="get">
            <div class="form-group">
                <label class="control-label">View all users</label>
                <input type="submit" name="view_users" value="view users" class="form-control btn-info" />
            </div>
        </form>
    </div>
    <p>
        <a asp-controller="Admin" asp-action="Index">start page</a>
    </p>
</div>

Event_planning/Views/Admin/UsersManagment.cshtml
@model IEnumerable<ApplicationUser>

@{
    ViewData["Title"] = "Users";
}

<h2>All users</h2>
<strong>
    Select users, that you want to remove
</strong>

<div class="container">
    <form asp-controller="Admin" asp-action="UsersManagment" method="post">
        @foreach (var user in Model)
        {
            <div class="row">
                <div class="col-md-1">
                    <input name="users_id" type="checkbox" value="@user.Id">
                </div>
                <div class="col-md-1">
                    <label>@user.UserName</label>
                </div>    
            </div>
        }
        <div class="col-md-2">
            <input type="submit" name="remove" value="remove" class="btn-info"/>
        </div>
    </form>
    <p>
        <a asp-controller = "Admin" asp-action="Index">start page</a>
    </p>
</div>